# Generated by Django 2.2.24 on 2021-10-16 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StoreList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='店舗名')),
                ('slug', models.SlugField(blank=True, null=True)),
                ('email', models.EmailField(max_length=254, verbose_name='メールアドレス')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50, verbose_name='名前')),
                ('user_age', models.IntegerField(verbose_name='年齢')),
                ('user_gender', models.IntegerField(verbose_name='性別')),
                ('user_email', models.EmailField(max_length=254, verbose_name='メールアドレス')),
                ('user_tel', models.CharField(max_length=20, verbose_name='電話番号')),
            ],
        ),
        migrations.CreateModel(
            name='Recruit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hourlywage', models.IntegerField(verbose_name='時給')),
                ('hourlywage_description', models.CharField(blank=True, max_length=50, verbose_name='時給詳細')),
                ('worktime', models.CharField(blank=True, max_length=50, verbose_name='勤務時間')),
                ('worktime_description', models.CharField(blank=True, max_length=100, verbose_name='勤務時間詳細')),
                ('description', models.TextField(blank=True, verbose_name='詳細')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.StoreList')),
            ],
        ),
    ]
