# Generated by Django 2.2.24 on 2021-11-02 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20211102_2253'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='store',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app.Recruit'),
        ),
        migrations.AlterField(
            model_name='recruit',
            name='recruitment_type',
            field=models.CharField(blank=True, max_length=50, verbose_name='職種'),
        ),
    ]
