# Generated by Django 2.2.24 on 2021-11-02 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20211102_2339'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='store',
            new_name='user_store',
        ),
    ]
