# Generated by Django 2.2.24 on 2021-11-03 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20211102_2348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storelist',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
