# Generated by Django 2.2.24 on 2021-11-03 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20211103_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_store',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
