# Generated by Django 2.2.24 on 2021-11-09 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20211103_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruit',
            name='publish',
            field=models.BooleanField(blank=True, null=True, verbose_name='公開する'),
        ),
    ]
