# Generated by Django 2.2.24 on 2021-11-15 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_recruit_publish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruit',
            name='hourlywage',
            field=models.CharField(max_length=50, verbose_name='給与'),
        ),
    ]
